# Generated by Django 3.2 on 2021-05-01 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20210501_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=32)),
                ('image_url', models.URLField(max_length=64)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='users.users', verbose_name='user')),
            ],
            options={
                'db_table': 'posting',
            },
        ),
    ]
