# Generated by Django 3.2 on 2021-05-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210501_0551'),
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posting',
            new_name='Postings',
        ),
    ]
