# Generated by Django 3.2 on 2021-05-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='content',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='posting',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
