# Generated by Django 3.2 on 2021-05-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('nickname', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
