# Generated by Django 3.2 on 2021-05-03 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(8)])),
                ('phone_number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
