# Generated by Django 3.2 on 2021-05-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_signup_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='nick_name',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
