# Generated by Django 3.2 on 2021-05-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=64, verbose_name='user e-mail')),
                ('name', models.CharField(max_length=32, verbose_name='use name')),
                ('password', models.CharField(max_length=32, verbose_name='password')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone number')),
                ('nickname', models.CharField(max_length=32, verbose_name='nickname')),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
