# Generated by Django 3.2 on 2021-05-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='create_time',
            new_name='create_at',
        ),
        migrations.AddField(
            model_name='users',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
