# Generated by Django 3.2 on 2021-05-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=80)),
                ('password', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=80, null=True)),
                ('nickname', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
