# Generated by Django 3.2 on 2021-05-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='user email')),
                ('password', models.CharField(max_length=50, verbose_name='user password')),
                ('username', models.CharField(blank=True, max_length=50, unique=True, verbose_name='user nickname')),
                ('phone_number', models.CharField(blank=True, max_length=17, unique=True, verbose_name='user phone number')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
