# Generated by Django 3.2 on 2021-05-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210504_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=65, verbose_name='user password'),
        ),
    ]
